### ISSUE TITLE
restore model

### ISSUE THREAD

**Issue by amanzotti** [tomcharnock/information_maximiser#4]
https://github.com/tomcharnock/information_maximiser/blob/8b49abdf3fb4c8baf77da2370c919097543ce6db/IMNN.py#L135

I think this is awesome as it is but does not work properly if for example, you have nn.x_ instead of nn.x having something flexible would be great.

**Comment by tomcharnock** [comment]
I've just pushed a major upgrade which allows you to upload data to a TensorFlow constant and work with only indices.
